#!/usr/bin/env bash
#This script displays numbers from 1 to 100
i=1
while [ $i -le 100 ]
do
	if [ $((i % 5)) -eq 0 ] && [ $((i % 3)) -eq 0 ]
	then
		echo "FizzBuzz"
		i=$(( i + 1 ))
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
		i=$((i + 1))
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
		i=$((i + 1))
	else
		echo "$i"
		i=$(( i + 1 ))
	fi
done
