#!/usr/bin/env bash
#a script that displays the time for 12 hours 59 minutes
i=0
while [ $i -le 12 ]
do
    echo "Hour: $i"
	n=1
    while [ $n -lt 60 ]
	do
		echo "$n"
		n=$((n + 1))
	done
	n=$((i + 1))
done 
